name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --frozen --all-extras
      - name: Format with ruff
        run: uv run ruff format --diff
      - name: Lint with ruff
        run: uv run ruff check --diff
      - name: Type check with pyright
        run: uv run pyright
